# Site settings

# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input: GFM


# Permalinks
permalink:        pretty
-- relative_permalinks: true


# Setup
title:            "RSMA Labs and Tutorials"
tagline:          'CMU Fall 2018'

email: 			daragh@daraghbyrne.me

description:     "A series of guides, tutorials and labs to accompany CMU's <a href='https://jmarsico.github.io/rsma2018/'>RSMA 2018 course</a>; a hands-on introductory course exploring the Media Architecture and Experiential Media."
--url:              https://jmarsico.github.io/rsmalabs
baseurl:          ""
--baseurl:          /rsmalabs

author:
  name:           'Jakob Marsico'
  email: 		  jake@ulrstudio.com
  url:            https://jmarsico.github.io/rsmalabs

course_site:      https://jmarsico.github.io/rsma2018


email: 			  jake@ulrstudio.com
twitter_username: 
github_username:  jmarsico

paginate:         5

# Custom vars
version:          1.0.0

github:
  user:           jmarsico
  repo:           https://github.com/jmarsico/rsmalabs
  
  

  
# The left menu bar
menu:
    items:
      - text: "Introduction"
        relativeUrl: /
      - text: "1. First Section Number sequentially"
        relativeUrl: /1-copy-this-folder/
        items:
          - text: "Tutorial: First Sketch - These can be nested as an array"
            relativeUrl: /1-copy-this-folder/first-sketch
      - text: "Tips and Troubleshooting"
        relativeUrl: /tips-and-troubleshooting/
      - text: "Resources"
        relativeUrl: /resources/
      - text: "FAQ"
        relativeUrl: /faq/
      - text: "DIoT 2017"
        absoluteUrl: http://daraghbyrne.github.io/diot2017


